In [17]:
import numpy as np
import matplotlib.pyplot as plt
from PIL import Image
import os
rootDir = "pht2"
fileCount = len([iq for iq in os.scandir(rootDir)])
print(fileCount)
#arr = np.arange(200,200,3)
for dirName, subdirList, fileList in os.walk(rootDir):
    print('Found directory: %s' % dirName)

21
Found directory: pht2


In [19]:
#def resize_images():
lis = []
for fname in fileList:
    im= Image.open(dirName+"\\"+fname)
    #im.show()
    im.resize((200,200))
    im1 = np.array(im)
    lis.append(im1)
arr = np.array(im)
arr
#print(lis)


array([[[161, 215, 191],
        [161, 215, 191],
        [162, 216, 192],
        ...,
        [187, 192, 160],
        [187, 192, 160],
        [186, 191, 159]],

       [[161, 215, 191],
        [161, 215, 191],
        [162, 216, 192],
        ...,
        [187, 192, 160],
        [186, 191, 159],
        [186, 191, 159]],

       [[161, 215, 191],
        [161, 215, 191],
        [162, 216, 192],
        ...,
        [187, 192, 160],
        [186, 192, 158],
        [186, 192, 158]],

       ...,

       [[204, 201, 148],
        [193, 192, 136],
        [189, 190, 133],
        ...,
        [159, 198, 141],
        [165, 204, 147],
        [170, 208, 151]],

       [[207, 204, 151],
        [195, 194, 138],
        [189, 190, 133],
        ...,
        [163, 202, 145],
        [168, 205, 151],
        [171, 208, 154]],

       [[210, 207, 152],
        [197, 196, 140],
        [190, 191, 134],
        ...,
        [165, 204, 149],
        [169, 206, 152],
        [172, 209, 155]]

In [11]:
lis[0].shape

(381, 678, 3)

In [28]:
arr1 = np.resize(lis[0],(512,512,3))

In [31]:
arr1.shape

(512, 512, 3)

In [35]:
#must need to import panadas
import pandas as pd
obj = pd.Series([4,7,-5,3])
print(obj)

0    4
1    7
2   -5
3    3
dtype: int64


In [39]:
sales = pd.Series([100, 200, 100, 400],
                  index = ['Jan', 'Feb', 'Mar', 'Apr'], name = '4 Months')
print(sales)
print(sales.values)

Jan    100
Feb    200
Mar    100
Apr    400
Name: 4 Months, dtype: int64
[100 200 100 400]


In [47]:
sw1 = pd.Series([20,30,20,25,30,40,0], 
              index = ['Mon', 'tue', 'wed', 'thur', 'Fri', 'sat', 'sun'])
print(sw)

Mon     20
tue     30
wed     20
thur    25
Fri     30
sat     40
sun      0
dtype: int64


In [42]:
import pandas as pd
import calendar as cal
print(cal.month_name[1])
d = list(range(1,8))
print(d)
sw = pd.Series([20,30,20,25,30,40,0], 
              index = list(range(1,8)))
print(sw)

January
[1, 2, 3, 4, 5, 6, 7]
1    20
2    30
3    20
4    25
5    30
6    40
7     0
dtype: int64


In [53]:
sw * 2

Mon     40
tue     60
wed     40
thur    50
Fri     60
sat     80
sun      0
dtype: int64

In [48]:
print(sw[[3,5]])
print(sw1[['Mon', 'tue']])

thur    25
sat     40
dtype: int64
Mon    20
tue    30
dtype: int64


In [52]:
sdata = {'Sindh': 3500, 'Punjab':4500, 'KPK': 3000, 'Balochistan':2000}
tax_by = pd.Series(sdata, 
                   index = ["Punjab", "Sindh", "KPK", "Balochistan", "GB"])
print(tax_by)
print(pd.isnull(tax_by))

Punjab         4500.0
Sindh          3500.0
KPK            3000.0
Balochistan    2000.0
GB                NaN
dtype: float64
Punjab         False
Sindh          False
KPK            False
Balochistan    False
GB              True
dtype: bool


In [55]:
#The new method of project managment ajile (SCARM, REGULATION)

In [56]:
sales = pd.Series([100, 200, 100, 400],
                  index = ['Jan', 'Feb', 'Mar', 'Apr'], name = '4 Months')
print(sales)
print(sales.values)

Jan    100
Feb    200
Mar    100
Apr    400
Name: 4 Months, dtype: int64
[100 200 100 400]
